
spring:
  grpc:
#    server:
#      port: 8000
    client:
      demo-server:
        host: localhost
        port: 9000
#        keep-alive-time: 20
#        keep-alive-timeout: 10
#        keep-alive-without-calls: true
#        max-inbound-message-size: 4194304
#        max-retry-attempts: 0
#        idleTimeout: 1800
#        plaintext: true
#        defaultTimeout: 60


